name: Translating strings
on: 
  push:
    branches:
      - develop
    paths:
      - 'locales/**'
      - '!locales/*.pot'

jobs:     
  extract-templates:
    name: Extract strings to translate
    runs-on: ubuntu-latest
    env:
      plugin_name: ${{ vars.PLUGIN_NAME }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependecies
        run: sudo apt-get install -y gettext
      - name: Extracting strings
        run: bash ./tools/generate_locales.sh
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: 'placeholder'
      - name: Commit and push changes
        run: |
          git config --global user.name "FrancisTicgal"
          git config --global user.email "francisco@ticgal.com"
          git remote set-url origin git@github.com:FrancisTicgal/myplugin.git
          git checkout develop
          git add locales/$plugin_name.pot
          git commit -m "Pot updated"
          git push